### ISSUE TITLE
add package.json file

### ISSUE THREAD

**Issue by ahadinia** [mamad3212/just-for-Practice#2]
اطلاعات هر پروژه جاوااسکریپتی توی فایل package.json باید باشه. این فایل با دستور `npm init` یا `yarn init` ساخته میشه.

لینک: https://www.geeksforgeeks.org/npm-init/

**Comment by mamad3212** [comment]
Done Upload Package.jason

**Comment by ahadinia** [comment]
فقط اون همه `dependencies` رو از کجا آورده بودی؟!

**Comment by mamad3212** [comment]
با همون کدی که خودش آموزش داده برای ایجاد فایل پیکیج . جیسون اینجور شد حتی
برای خود کسی که داشت آموزش میداد اینجور نبود
چند بار هی نوشتم پاک کردم دیدم خودش اضافه میکنه

‫‪Mostafa Ahadinia‬‏ ***@***.***‬‏> در تاریخ جمعه ۲۰ دسامبر
۲۰۲۴ ساعت ۲۲:۳۲ نوشت:‬
