### ISSUE TITLE
return html file as response

### ISSUE THREAD

**Issue by ahadinia** [mamad3212/just-for-Practice#3]
توی سرور node که راه انداختیم، با `GET` روی مسیر `/` یه صفحه html خونده بشه و به عنوان پاسخ ارسال بشه.

برای خوندن یه فایل باید از تابع `fs.readFileSync` استفاده بشه.

توی صفحه html بخشی که تیتر هست رو اینجوری بذار: `__title__` و بخشی که متن هست رو اینجوری: `__content__`.
باید دو متغیر title و content توی js تعریف کنی که با متن‌های مشخص شده توی فایل html جایگزین بشن.

لینک‌ها:
- https://www.geeksforgeeks.org/node-js-fs-readfilesync-method/
- https://www.w3schools.com/nodejs/nodejs_filesystem.asp

**Comment by mamad3212** [comment]
got into trouble

**Comment by mamad3212** [comment]
add .gitignore file.fix #3

**Comment by ahadinia** [comment]
فایل `index.html` به عنوان template در نظر گرفت شده. یعنی باید __title__ و  __content__ عوض بشن
